
// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire n_0, n_1, n_2, n_3;
  nand g133 (N22, n_0, n_3);
  nand g134 (N23, n_2, n_3);
  nand g135 (n_3, N2, n_1);
  nand g136 (n_2, N7, n_1);
  nand g137 (n_0, N3, N1);
  nand g138 (n_1, N3, N6);
endmodule

