
// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire n_0, n_1, n_2, n_3;
  NAND2X1 g133(.A (n_3), .B (n_0), .Y (N22));
  NAND2X1 g134(.A (n_3), .B (n_2), .Y (N23));
  NAND2X1 g135(.A (n_1), .B (N2), .Y (n_3));
  NAND2X1 g136(.A (n_1), .B (N7), .Y (n_2));
  NAND2X1 g137(.A (N1), .B (N3), .Y (n_0));
  NAND2X1 g138(.A (N6), .B (N3), .Y (n_1));
endmodule

