
// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  not g50 (N22, n_5);
  wire w;
  nand g52 (N23, w, n_4);
  or g (w, n_2, n_1);
  wire w0;
  nor g51 (n_5, w0, n_3);
  and g0 (w0, N3, N1);
  not g53 (n_4, n_3);
  nor g54 (n_3, n_2, n_0);
  and g55 (n_2, N3, N6);
  not g57 (n_1, N7);
  not g56 (n_0, N2);
endmodule

