
// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1

// Verification Directory fv/c17 

module c17(N1, N2, N3, N6, N7, N22, N23);
  input N1, N2, N3, N6, N7;
  output N22, N23;
  wire N1, N2, N3, N6, N7;
  wire N22, N23;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  INVX1 g50(.A (n_5), .Y (N22));
  OAI21X1 g52(.A (n_1), .B (n_2), .C (n_4), .Y (N23));
  AOI21X1 g51(.A (N1), .B (N3), .C (n_3), .Y (n_5));
  INVX1 g53(.A (n_3), .Y (n_4));
  NOR2X1 g54(.A (n_0), .B (n_2), .Y (n_3));
  AND2X2 g55(.A (N6), .B (N3), .Y (n_2));
  INVX1 g57(.A (N7), .Y (n_1));
  INVX1 g56(.A (N2), .Y (n_0));
endmodule

