set search_path "/synopsys/GPDK/SAED_EDK90nm/Digital_Standard_Cell_Library/synopsys/models"
set link_library "saed90nm_max.db"
set target_library "saed90nm_max.db"
set symbol_library "saed90nm_max.db"
analyze -library WORK -format verilog {/ugrad/dolsen/Git/ECE524/Lab1/c6288.v}
elaborate C17 -architecture BEHAVE -library WORK
write -hierarchy -format verilog -output /ugrad/dolsen/Git/ECE524/Lab1/c6288Gen.v
link
compile -exact_map
write -hierarchy -format verilog -output /ugrad/dolsen/Git/ECE524/Lab1/c6288Map.v
report_area > areaC6288.txt
remove_design c6288
