set search_path "/synopsys/GPDK/SAED_EDK90nm/Digital_Standard_Cell_Library/synopsys/models"
set link_library "saed90nm_max.db"
set target_library "saed90nm_max.db"
set symbol_library "saed90nm_max.db"
analyze -library WORK -format vhdl {/ugrad/dolsen/Git/ECE524/Lab1/FullAdder.vhd}
elaborate FULLADDER -architecture BEHAVE -library WORK
write -hierarchy -format verilog -output /ugrad/dolsen/Git/ECE524/Lab1/FullAdderGen.v
link
compile -exact_map
write -hierarchy -format verilog -output /ugrad/dolsen/Git/ECE524/Lab1/FullAdderMap.v
report_area > areaFA.txt
remove_design FullAdder
