
// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1

// Verification Directory fv/FullAdder 

module FullAdder(X, Y, Cin, Cout, Sum);
  input X, Y, Cin;
  output Cout, Sum;
  wire X, Y, Cin;
  wire Cout, Sum;
  wire w, w0, w1, w2, w3, w4, w5, w6;
  wire w7, w8, w9, w10, w11, w12;
  nand g13 (Sum, w6, w12);
  or g12 (w12, w11, Cin);
  and g11 (w11, w8, w10);
  nand g10 (w10, w9, X);
  not g9 (w9, Y);
  nand g8 (w8, w7, Y);
  not g7 (w7, X);
  nand g6 (w6, w3, w5, Cin);
  nand g5 (w5, w4, X);
  not g4 (w4, Y);
  nand g3 (w3, w2, Y);
  not g2 (w2, X);
  nand g63 (Cout, w0, w1);
  nand g1 (w1, Cin, X);
  nand g0 (w0, w, Y);
  or g (w, Cin, X);
endmodule

