
// Generated by Cadence Encounter(R) RTL Compiler RC12.22 - v12.20-s014_1

// Verification Directory fv/FullAdder 

module FullAdder(X, Y, Cin, Cout, Sum);
  input X, Y, Cin;
  output Cout, Sum;
  wire X, Y, Cin;
  wire Cout, Sum;
  FAX1 g63(.A (Y), .B (X), .C (Cin), .YC (Cout), .YS (Sum));
endmodule

